### PR TITLE
ALX commits

### PR DESCRIPTION
**Pull request by Boutchouangemmanuel**

### CODE REVIEW

**Comment by Boutchouangemmanuel** [comment]
close request

**Comment by Boutchouangemmanuel** [comment]
ALX COMMITS

**Comment by Boutchouangemmanuel** [comment]
ALX COMMITS

**Review by Zelipha — COMMENTED** [review]
what is this

**Comment by Boutchouangemmanuel** [comment]
Sorry an error


Le ven. 28 avr. 2023 à 18:53, Zelipha Wambui ***@***.***> a
écrit :

**Comment by Boutchouangemmanuel** [comment]
delete it if possible

**Pull request closed without merging**
